version: '3'
services:
  golang:
    build:
      context: .
      args:
        USER: gocker
        UID: 1000
    image: gocker
    volumes:
      - ./go:/go
    command: sh ./start.sh
    env_file:
      - .env
